### ISSUE TITLE
version 0.09 ?

### ISSUE THREAD

**Issue by tissatussa** [udhos/capivara#5]
In the CCRL list https://www.computerchess.org.uk/ccrl/4040/rating_list_all.html i find "Capivara LK 0.09b02f 64-bit", which seems a newer version then the one at these GitHub pages .. can you explain ?

**Comment by udhos** [comment]
That Capivara engine is another chess engine, in C++, with the same name:

https://www.chessprogramming.org/Capivara

Unfortunately I have picked an existing chess engine name for this repository, hence the name clash.
